### ISSUE TITLE
Translate `docs/how_to_contribute.md` to English

### ISSUE THREAD

**Issue by wangeguo** [amphitheatre-app/playground#14]

**Comment by lispking** [comment]
assign to me @wangeguo

**Comment by wangeguo** [comment]
I believe that the current document combines the topics of "Contributing" and "Reward." To enhance clarity, we should emphasize "Reward" and extract the aspects of contribution, consolidating them cohesively.

As per our plan, there is a comprehensive guide available at: [Global Contributing Guideline Link](https://docs.amphitheatre.app/contributing/). Additionally, for each specific project, we intend to include a `CONTRIBUTING.md` file following GitHub's best practices; see [CONTRIBUTING.md](https://github.com/amp-buildpacks/.github/blob/main/CONTRIBUTING.md).

Furthermore, a brief entry point for contributing will be provided in the `README.md` file of each project.

By incorporating these changes, we aim to create a more organized and clear document structure. Contributors should find it easier to locate the information they need.
