### ISSUE TITLE
制定前端选型和方案 

### ISSUE THREAD

**Issue by jueduizone** [amphitheatre-app/playground#3]
我们需要你：
1. 与后端贡献者沟通，评估技术选型和参考的方案，这里建议参考：[Rust Playground](https://github.com/amphitheatre-app/playground/issues?q=is%3Aopen+is%3Aissue+label%3ATask)
2. 根据选型和方案，搭建初始工程，并拆解成关键开发任务
3. 预估整体开发周期

> 如果你感兴趣，请在下方回复你的预计完成时间（小时），我们将根据时间支付你一定的激励，详情参考[ Readme](https://github.com/amphitheatre-app/playground)

**Comment by peewee92** [comment]
1. 项目搭建、配置： vite + react + @monaco-editor/react：1小时
2. 界面、组件开发： 8小时（参照 [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021)
3. api对接联调：4小时
技术选型加需求拆分花费：1小时
