### ISSUE TITLE
界面及组件开发

### ISSUE THREAD

**Issue by jueduizone** [amphitheatre-app/playground#6]
根据已有工程，参照 [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021) 进行界面开发，当前版本需要支持：
1. RUN 功能
2. CONFIG
3. CHAIN（选择对应的链）

以上仅指页面实现和交互，具体实现由后端 API 实现，API 的对接调试会单独作为任务

> 如果你感兴趣，请在下方回复你的预计完成时间（小时），我们将根据时间支付你一定的激励，详情参考[ How To Contribute](https://github.com/amphitheatre-app/playground/blob/master/docs/how_to_contribute.md)

**Comment by lispking** [comment]
前端为什么不用 NextJS？比较建议用这个，还可以复用现有React生态的所有组件，很多大厂都在使用，而且14版本用Rust优化后，性能更佳，建议更改框架后再执行该issue

**Comment by jueduizone** [comment]
> 前端为什么不用 NextJS？比较建议用这个，还可以复用现有React生态的所有组件，很多大厂都在使用，而且14版本用Rust优化后，性能更佳，建议更改框架后再执行该issue

能否直接帮忙改成 NextJS?

**Comment by lispking** [comment]
> > 前端为什么不用 NextJS？比较建议用这个，还可以复用现有React生态的所有组件，很多大厂都在使用，而且14版本用Rust优化后，性能更佳，建议更改框架后再执行该issue
> 
> 能否直接帮忙改成 NextJS?

可以，不过要看当初用 `vite` 的选型原因是？

**Comment by wangeguo** [comment]
Components have been abstracted to standalone projects https://github.com/amphitheatre-app/playground-react
